// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241018120346_Labo10")]
    partial class Labo10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework.Entities.Auteur", b =>
                {
                    b.Property<int>("AuteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuteurId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AuteurId");

                    b.ToTable("auteurs");

                    b.HasData(
                        new
                        {
                            AuteurId = -1,
                            Nom = "Durant",
                            Prenom = "Pierre"
                        },
                        new
                        {
                            AuteurId = -2,
                            Nom = "Nothomb",
                            Prenom = "Amelie"
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Bibliotheque", b =>
                {
                    b.Property<int>("BibliothequeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BibliothequeId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroTelephone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BibliothequeId");

                    b.ToTable("bibliotheques");

                    b.HasData(
                        new
                        {
                            BibliothequeId = -1,
                            Adresse = "Rue du Paradis, 5 1400 Nivelles",
                            Nom = "Librairie Georges",
                            NumeroTelephone = "+32 68 36 72 98"
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Livre", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivreId"));

                    b.Property<DateOnly>("DateParution")
                        .HasColumnType("date");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ISBN")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("DECIMAL(9, 2)");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LivreId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("livres");

                    b.HasData(
                        new
                        {
                            LivreId = -1,
                            DateParution = new DateOnly(2015, 10, 25),
                            Genre = "Thriller",
                            ISBN = 1234,
                            PrixVente = 19.99m,
                            Titre = "Coup de feu"
                        },
                        new
                        {
                            LivreId = -2,
                            DateParution = new DateOnly(2015, 10, 25),
                            Genre = "Romantique",
                            ISBN = 1235,
                            PrixVente = 19.99m,
                            Titre = "Coup de foudre"
                        },
                        new
                        {
                            LivreId = -3,
                            DateParution = new DateOnly(2015, 10, 25),
                            Genre = "Porno",
                            ISBN = 1236,
                            PrixVente = 19.99m,
                            Titre = "Coup de fouet"
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.LivreAuteur", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "AuteurId");

                    b.HasIndex("AuteurId");

                    b.ToTable("livreAuteurs");

                    b.HasData(
                        new
                        {
                            LivreId = -1,
                            AuteurId = -1
                        },
                        new
                        {
                            LivreId = -2,
                            AuteurId = -1
                        },
                        new
                        {
                            LivreId = -3,
                            AuteurId = -1
                        },
                        new
                        {
                            LivreId = -3,
                            AuteurId = -2
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Pret", b =>
                {
                    b.Property<int>("PretId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PretId"));

                    b.Property<int>("BibliothequeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateDebut")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DateFin")
                        .HasColumnType("date");

                    b.Property<int>("EmprunteurId")
                        .HasColumnType("int");

                    b.Property<bool>("EstRendu")
                        .HasColumnType("bit");

                    b.HasKey("PretId");

                    b.HasIndex("BibliothequeId");

                    b.HasIndex("EmprunteurId");

                    b.ToTable("prets");
                });

            modelBuilder.Entity("EntityFramework.Entities.PretLivre", b =>
                {
                    b.Property<int>("PretId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("PretId", "LivreId");

                    b.HasIndex("LivreId");

                    b.ToTable("pretsLivres");
                });

            modelBuilder.Entity("EntityFramework.Entities.StockLivre", b =>
                {
                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<int>("BibliothequeId")
                        .HasColumnType("int");

                    b.Property<int>("StockAchat")
                        .HasColumnType("int");

                    b.Property<int>("StockLocation")
                        .HasColumnType("int");

                    b.HasKey("LivreId", "BibliothequeId");

                    b.HasIndex("BibliothequeId");

                    b.ToTable("stockLivres");

                    b.HasData(
                        new
                        {
                            LivreId = -1,
                            BibliothequeId = -1,
                            StockAchat = 10,
                            StockLocation = 10
                        },
                        new
                        {
                            LivreId = -2,
                            BibliothequeId = -1,
                            StockAchat = 10,
                            StockLocation = 10
                        },
                        new
                        {
                            LivreId = -3,
                            BibliothequeId = -1,
                            StockAchat = 10,
                            StockLocation = 10
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurId"));

                    b.Property<string>("AccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("MaxRefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilisateurId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utilisateurs");

                    b.HasData(
                        new
                        {
                            UtilisateurId = -1,
                            Email = "hello@gmail.com",
                            MotDePasse = "$2a$11$8AaJxUgo7ifbZZHsrVEn5O/jRhcYvAvZqfSkHf29IDDAqw//7p346",
                            Nom = "Noel",
                            Prenom = "Benjamin",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("EntityFramework.Entities.Vente", b =>
                {
                    b.Property<int>("VenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VenteId"));

                    b.Property<int>("AcheteurId")
                        .HasColumnType("int");

                    b.Property<int>("BibliothequeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateVente")
                        .HasColumnType("date");

                    b.HasKey("VenteId");

                    b.HasIndex("AcheteurId");

                    b.HasIndex("BibliothequeId");

                    b.ToTable("ventes");
                });

            modelBuilder.Entity("EntityFramework.Entities.VenteLivre", b =>
                {
                    b.Property<int>("VenteId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrixVente")
                        .HasColumnType("DECIMAL(9, 2)");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("VenteId", "LivreId");

                    b.HasIndex("LivreId");

                    b.ToTable("venteLivres");
                });

            modelBuilder.Entity("EntityFramework.Entities.LivreAuteur", b =>
                {
                    b.HasOne("EntityFramework.Entities.Auteur", "Auteur")
                        .WithMany("LivreAuteur")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivreAuteur_Auteur");

                    b.HasOne("EntityFramework.Entities.Livre", "Livre")
                        .WithMany("LivreAuteur")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LivreAuteur_Livre");

                    b.Navigation("Auteur");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("EntityFramework.Entities.Pret", b =>
                {
                    b.HasOne("EntityFramework.Entities.Bibliotheque", "Bibliotheque")
                        .WithMany("Prets")
                        .HasForeignKey("BibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pret_Bibliotheque");

                    b.HasOne("EntityFramework.Entities.Utilisateur", "Emprunteur")
                        .WithMany("Emprunts")
                        .HasForeignKey("EmprunteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pret_Utilisateur");

                    b.Navigation("Bibliotheque");

                    b.Navigation("Emprunteur");
                });

            modelBuilder.Entity("EntityFramework.Entities.PretLivre", b =>
                {
                    b.HasOne("EntityFramework.Entities.Livre", "Livre")
                        .WithMany("PretLivre")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PretLivre_Livre");

                    b.HasOne("EntityFramework.Entities.Pret", "Pret")
                        .WithMany("PretLivre")
                        .HasForeignKey("PretId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PretLivre_Pret");

                    b.Navigation("Livre");

                    b.Navigation("Pret");
                });

            modelBuilder.Entity("EntityFramework.Entities.StockLivre", b =>
                {
                    b.HasOne("EntityFramework.Entities.Bibliotheque", "Bibliotheque")
                        .WithMany("StockLivre")
                        .HasForeignKey("BibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StockLivre_Bibliotheque");

                    b.HasOne("EntityFramework.Entities.Livre", "Livre")
                        .WithMany("StockLivre")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_StockLivre_Livre");

                    b.Navigation("Bibliotheque");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("EntityFramework.Entities.Vente", b =>
                {
                    b.HasOne("EntityFramework.Entities.Utilisateur", "Acheteur")
                        .WithMany("Achats")
                        .HasForeignKey("AcheteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vente_Utilisateur");

                    b.HasOne("EntityFramework.Entities.Bibliotheque", "Bibliotheque")
                        .WithMany("Ventes")
                        .HasForeignKey("BibliothequeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vente_Bibliotheque");

                    b.Navigation("Acheteur");

                    b.Navigation("Bibliotheque");
                });

            modelBuilder.Entity("EntityFramework.Entities.VenteLivre", b =>
                {
                    b.HasOne("EntityFramework.Entities.Livre", "Livre")
                        .WithMany("VenteLivre")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VenteLivre_Livre");

                    b.HasOne("EntityFramework.Entities.Vente", "Vente")
                        .WithMany("VenteLivre")
                        .HasForeignKey("VenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VenteLivre_Emprunt");

                    b.Navigation("Livre");

                    b.Navigation("Vente");
                });

            modelBuilder.Entity("EntityFramework.Entities.Auteur", b =>
                {
                    b.Navigation("LivreAuteur");
                });

            modelBuilder.Entity("EntityFramework.Entities.Bibliotheque", b =>
                {
                    b.Navigation("Prets");

                    b.Navigation("StockLivre");

                    b.Navigation("Ventes");
                });

            modelBuilder.Entity("EntityFramework.Entities.Livre", b =>
                {
                    b.Navigation("LivreAuteur");

                    b.Navigation("PretLivre");

                    b.Navigation("StockLivre");

                    b.Navigation("VenteLivre");
                });

            modelBuilder.Entity("EntityFramework.Entities.Pret", b =>
                {
                    b.Navigation("PretLivre");
                });

            modelBuilder.Entity("EntityFramework.Entities.Utilisateur", b =>
                {
                    b.Navigation("Achats");

                    b.Navigation("Emprunts");
                });

            modelBuilder.Entity("EntityFramework.Entities.Vente", b =>
                {
                    b.Navigation("VenteLivre");
                });
#pragma warning restore 612, 618
        }
    }
}
